### PR TITLE
feat(#57): disable `supermaven-nvim` on condition

### LINKED ISSUE #57: [Suggestion] ignoring files (not filetypes) dynamically
`ignore_filetypes` currently is limited to filetypes, but in some cases, I want to disable the plugin from running on some specific files. For example, some shellscript files that contains some secrets, token, etc… 

If I add `bash = true` in `ignore_filetypes` then this will disable it for all bash files. I don't want this. I want to be able to do something like this instead

```lua
function()
   return string.match(vim.fn.expand('%:t'), 'foo.sh') != nil
end

### PR DESCRIPTION
**Pull request by AlejandroSuero**
With these changes the user can stop `supermaven` conditionally for example, if the user wants files like `bash_private.sh` to not be running but want any other `.sh` files to have `supermaven` running it can do it with the following configuration.

```lua
require("supermaven-nvim").setup({
  condition = function()
    return string.match(vim.fn.expand(":t"), "_private.sh")
  end,
})
```

- [x] Updated `README.md` with changes

---

For this demo I used:

```lua
require("supermaven-nvim").setup({
  condition = function()
    return vim.fn.expand(":t:r") == "api"
  end,
})
```

https://github.com/supermaven-inc/supermaven-nvim/assets/71392160/a1efb698-8e5b-49a2-af39-d2b5887fc492

> [!NOTE]
> It runs on `lua` files except in `api.lua` because the filename is `api`.

Closes #57.

### CODE REVIEW

**Comment by ahmedelgabri** [comment]
@AlejandroSuero sorry I was a bit busy. Just tried the changes here, for some reason it doesn't work for me. 

Here is my how I'm testing it


```lua
{
	'https://github.com/AlejandroSuero/supermaven-nvim',
	branch = 'feature/conditional-running',
	config = function()
		require('supermaven-nvim').setup {
			keymaps = {
				accept_suggestion = '<C-g>',
				condition = function()
					local match = vim.bo.filetype == 'starter'
						or vim.fn.expand ':t:r' == 'init'
					return match
				end,
			},
			disable_inline_completion = false, -- disables inline completion for use with cmp
			disable_keymaps = false, -- disables built in keymaps for more manual control
		}
	end,
},
```

You can here for example that although I have a check for the `starter` filetype it still ran (check the supermaven message at the bottom), same happens when opening any `init.lua`, the condition should prevent it from running but it's still running

https://github.com/supermaven-inc/supermaven-nvim/assets/63876/7a5de70e-4348-45b6-8b74-77e8226dd0c1

**Comment by AlejandroSuero** [comment]
@ahmedelgabri `condition` should be outside the `keymaps` entry, like:

```lua
require("supermaven-nvim").setup({
  keymaps = {
    - - ...
   },
  condition = function()
     return - - your condition
  end,
})
```

Try it out this way and if something fails, I'll check it out tomorrow, today I don't have the pc around.

**Comment by ahmedelgabri** [comment]
What a stupid mistake 🤦‍♂️ I will try again in the evening. Thanks @AlejandroSuero

**Comment by AlejandroSuero** [comment]
@ahmedelgabri no worries, I should have put an example with the other options in the PR description so it doesn't lead to confusion.

**Comment by ahmedelgabri** [comment]
@AlejandroSuero works great! 👍🏼

**Comment by ahmedelgabri** [comment]
@AlejandroSuero any estimations when this will be merged?

**Pull request merged**
