### PR TITLE
feat(#18): add `silence_info` and created `logger` to write to a log file

### LINKED ISSUE #18: Add config option to silence "Supermaven ... is running"
Hey,

I would appreciate it if there was an option to silence the `Supermaven Pro is running` message. It's just noisy and doesn't really provide any value for me.

Cheers!

### LINKED ISSUE #42: Possible to suppress log "Supermaven Pro is running." when loading?
Would there be any way to suppress the log `Supermaven Pro is running.` when loading up the plugin?

### PR DESCRIPTION
**Pull request by AlejandroSuero**
# Changes made

- [x] Added `logger` inspired by [none-ls](https://github.com/nvim-tools/none-ls.nvim) but without the use of [plenary.nvim](https://github.com/nvim-lua/plenary.nvim).
- [x] Made changes to the config to ease the use of a logger and validate the config and add user level settings to control when and what to show.
- [x] Changed the files that printed information to use `logger` with the level warning.
- [x] Made corresponding changes in the `README`.

## Demo of the changes

- With `silence_info` and `debug` on:

https://github.com/supermaven-inc/supermaven-nvim/assets/71392160/0be8797b-d6fa-4cb2-b6bd-beae5c57539b

- With `silence_info` and `debug` off:

https://github.com/supermaven-inc/supermaven-nvim/assets/71392160/d3300bde-9a8d-420d-9dd3-3a85187f479a

## How to use the logger

1. Import the logger `local log = require("supermaven-nvim.logger")`.
2. Decide which level of information you want the user to see.
  - Levels:
    - "error": Always shows.
    - "warn": Always shows.
    - "info": Always shows. (like `print`)
    - "debug": shows if `debug` is true.
    - "trace": shows if `silence_info` is true.
    - "off": logger turned off completely `log_level` option is set too `"off"`.
3. If you have them set to `debug = true` or/and silenced info, `:SupermavenShowLog` to show the log file with timestamps and the level off error.
4. If you want to reset or clear the log file, `:SupermavenClearLog`.

Closes #18
Closes #42

### CODE REVIEW

**Comment by joaomendoncaa** [comment]
Hey @sm-victorw, if you could take a look at this PR to potentially move it forward it would be amazing since it solves both #42 and #4 (which are both _small but annoying_ quirks). 

Sorry for the bump but it was in hopes you had custom notifications and had this wasn't on your backlog.

Appreciate your time.

**Comment by sm-victorw** [comment]
@AlejandroSuero would it be possible to have the verbosity for the logger controlled through a single config option, particularly `log_level`? Having 3 separate boolean values to control what get printed feels rather unintuitive.

I have in mind that e.g. `log_level` taking values "off", "silent", "warn", or "debug" or something similar would be more manageable

**Comment by AlejandroSuero** [comment]
@sm-victorw I made the changes so now it just needs to be

```lua
-- supermaven opts
{
  keymaps = {
    -- ...
  },
  log_level = "off" -- based on `vim.log.levels[log_level:upper()]`
}
```

if `off` silence all expect warnings and errors.

**Review by sm-victorw — APPROVED** [review]

**Comment by maksimmuravev** [comment]
How can I turn off the welcome message?
```
[supermaven-nvim] Starting Supermaven...
Press ENTER or type command to continue
```

**Pull request merged**
